[package]
name = "audiosep-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.16.0"
rfd = "0.7.0"
hound = "3.4.0"
dasp = "0.11.0"
file-format = "0.6.0"
